# NextGenRail API Configuration
# Default configuration for all environments

server:
  port: 8080
  servlet:
    context-path: /api
  error:
    include-message: always
    include-binding-errors: always

spring:
  application:
    name: nextgenrail-api
  
  # MongoDB Configuration
  data:
    mongodb:
      uri: mongodb+srv://bhumika-aga:test@movie.elou1o4.mongodb.net/nextgenrail
      auto-index-creation: true
  
  # Security Configuration
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${JWT_ISSUER:http://localhost:8080}
  
  # Mail Configuration (for OTP)
  mail:
    host: ${MAIL_HOST:smtp.gmail.com}
    port: ${MAIL_PORT:587}
    username: ${MAIL_USERNAME:}
    password: ${MAIL_PASSWORD:}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  
  # Cache Configuration
  cache:
    type: caffeine
    caffeine:
      spec: maximumSize=1000,expireAfterWrite=30m
  
  # Jackson Configuration
  jackson:
    default-property-inclusion: non_null
    time-zone: Asia/Kolkata

# JWT Configuration
jwt:
  secret: ${JWT_SECRET:mySecretKey123456789012345678901234567890}
  expiration: 86400000 # 24 hours in milliseconds
  refresh-expiration: 604800000 # 7 days in milliseconds

# API Documentation
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
  info:
    title: NextGenRail API
    description: Production-grade IRCTC clone backend
    version: 1.0.0
    contact:
      name: NextGenRail Team
      email: support@nextgenrail.com

# Application Configuration
app:
  name: NextGenRail
  version: 1.0.0
  description: Production-grade IRCTC clone
  
  # OTP Configuration
  otp:
    expiration: 300000 # 5 minutes in milliseconds
    length: 6
    
  # Booking Configuration
  booking:
    cancellation-hours: 2 # Cancel before 2 hours of departure
    waitlist-limit: 200
    
  # CORS Configuration
  cors:
    allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:3000}
    allowed-methods: GET,POST,PUT,DELETE,OPTIONS
    allowed-headers: "*"
    allow-credentials: true

# Logging Configuration
logging:
  level:
    com.nextgenrail: DEBUG
    org.springframework.security: DEBUG
    org.springframework.data.mongodb: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

# Management Endpoints
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: when-authorized