services:
  # Backend API Service
  - type: web
    name: irctc-plus-api
    runtime: docker
    dockerfilePath: ./apps/api/Dockerfile
    dockerContext: ./
    plan: free
    region: oregon
    branch: main
    healthCheckPath: /actuator/health
    autoDeploy: true
    buildFilter:
      paths:
        - apps/api/**
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: SERVER_PORT
        value: 10000
      - key: MONGODB_URI
        generateValue: true
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_REFRESH_SECRET
        generateValue: true
      - key: CORS_ALLOWED_ORIGINS
        value: https://irctc-plus.onrender.com,https://irctc-plus-web.onrender.com
      - key: JWT_EXPIRATION
        value: 86400
      - key: JWT_REFRESH_EXPIRATION
        value: 604800

  # Frontend Static Site
  - type: web
    name: irctc-plus-web
    runtime: static
    buildCommand: npm run build
    plan: free
    region: oregon
    branch: main
    autoDeploy: true
    buildFilter:
      paths:
        - apps/web/**
    envVars:
      - key: REACT_APP_API_BASE_URL
        value: https://irctc-plus-api.onrender.com
      - key: REACT_APP_WS_URL
        value: wss://irctc-plus-api.onrender.com
      - key: NODE_ENV
        value: production
